version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cetpro_web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mysql:8.0
    container_name: cetpro_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cetpro
      MYSQL_USER: cetpro_user
      MYSQL_PASSWORD: cetro_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: